Skip commit and deploy if build fails

diff --git a/.github/workflows/refresh-wordpress-major-and-beta.yml b/.github/workflows/refresh-wordpress-major-and-beta.yml
--- a/.github/workflows/refresh-wordpress-major-and-beta.yml
+++ b/.github/workflows/refresh-wordpress-major-and-beta.yml
@@ -12,8 +12,8 @@ on:
         - cron: '*/20 * * * *'
 
 jobs:
-    build_and_deploy:
-        # Only run this workflow from the trunk branch and when it's triggered by dmsnell OR adamziel
+    build_wordpress_major_and_beta_push_to_github_and_deploy_website:
+        # Only run this workflow from the trunk branch and when it's triggered by a maintainer listed below
         if: >
             github.ref == 'refs/heads/trunk' && (
                 github.actor == 'adamziel' ||
@@ -42,19 +42,29 @@ jobs:
               shell: bash
               env:
                   FORCE_REBUILD: ${{ github.event.inputs.force_rebuild }}
-              run: PATH="${PATH}:${HOME}/.bun/bin" npx nx bundle-wordpress:major-and-beta playground-wordpress-builds
+              run: |
+                  PATH="${PATH}:${HOME}/.bun/bin" npx nx bundle-wordpress:major-and-beta playground-wordpress-builds
+                  if [ $? -eq 0 ]; then
+                    echo "WordPress build succeeded"
+                    echo 'BUILD_FAILED=0' >> $GITHUB_OUTPUT
+                  else
+                    echo "WordPress build failed"
+                    echo 'BUILD_FAILED=1' >> $GITHUB_OUTPUT
+                  fi
             - name: Check for uncommitted changes
+              # Prevent commit if the build failed to avoid polluting the commit history
+              if: steps.changes.outputs.BUILD_FAILED == '0'
               id: changes
               run: |
                   if [ -z "$(git status --porcelain)" ]; then
                       echo "No changes"
-                      echo 'CHANGES=0' >> $GITHUB_OUTPUT
+                      echo 'COMMIT_CHANGES=0' >> $GITHUB_OUTPUT
                   else
                       echo "Changes detected"
-                      echo 'CHANGES=1' >> $GITHUB_OUTPUT
+                      echo 'COMMIT_CHANGES=1' >> $GITHUB_OUTPUT
                   fi
             - name: Push rebuilt WordPress to GitHub
-              if: steps.changes.outputs.CHANGES == '1'
+              if: steps.changes.outputs.COMMIT_CHANGES == '1'
               run: |
                   git config --global user.name "deployment_bot"
                   git config --global user.email "deployment_bot@users.noreply.github.com"
@@ -67,7 +77,7 @@ jobs:
                       git push origin HEAD:trunk
                   fi;
             - name: Deploy website
-              if: steps.changes.outputs.CHANGES == '1'
+              if: steps.changes.outputs.COMMIT_CHANGES == '1'
               uses: benc-uk/workflow-dispatch@v1
               with:
                   workflow: build-website.yml
